### ISSUE TITLE
Bug: search/autocomplete component value life cycle

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#1093] opened 2022-01-31 14:46 UTC
**Description**
This likely isn't a bug but rather an issue with my implementation. I hope using the bug template is okay.
Use case: We need a "peoplepicker" consisting of a `sbbInput` and the `sbb-autocomplete` component. I followed the [docs](https://angular.app.sbb.ch/angular/components/autocomplete/overview) and got it working quite well.

What happens: The `sbb-option`'s value is like this: `[value]="option"` (an object, not a string!). When selecting one of the autocomplete's items, the input emits a new value and causes the search to trigger again (with the "object value" and not a string). This will throw an error.
I tried a workaround (see repro) which works but seems to be error prone to future API changes.

**To Reproduce**
1. Go to [stackblitz example](https://stackblitz.com/edit/angular-ivy-eujdfa?devtoolsheight=33&file=src/app/app.component.html)
2. Type "Mario" into the input and select one of the results. The chosen user will appear below the h2 "selected user". This is the expected/working behavior.
3. Go to app.component.ts and comment out line 32 (filter). Repeat step 2.
It will work but throw an error in the console.

**Expected behavior**
I'd expect the input to not emit a value when a result was selected. I honestly don't know how the sbbInput and sbb-autocomplete influence each other, so I have a hard time debugging this.

The docs/examples are all with string values - is it discouraged to use autocomplete with object values?
Thanks for your help!

**Comment by kyubisation** [comment] 2022-02-01 08:58
Hello @sandrooco 
This is more or less the expected behavior of the autocomplete (with objects). It is up to you, to differentiate between string values and object values, since this naturally can happen (the user can select an option from the autocomplete list or type in the value via keyboard).

To provide a similar example from material (which has a similar implementation to ours): https://material.angular.io/components/autocomplete/examples#autocomplete-display

Is it ok to close this issue?

**Closed** 2022-02-15 09:28 UTC
Labels: question
