### ISSUE TITLE
[Bug]: sbb-link on button-Element is not viewed correctly on Apple iPad 10th, Safari / iOS 16 or lower

### ISSUE THREAD

**Issue by thm912** [sbb-design-systems/sbb-angular#1914] opened 2023-06-09 10:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Other

### Which version are you using

15.3.1

### Operating system

iOS 16

### Browser / Browser version

Safari 15.6

### Input mode

Other

### What happened?

The button with attribute "sbb-link" does not show the .sbb-button-right-icon --> svg in initial state. See "Informationen zu Klassen und Tarifkonditionen" which is a button with "sbb-link"-Attribute

Temporary workaround for us was to set top:0 and right:0 on the &lt;sbb-icon&gt;-Element in our component. 

![link-without-icon](https://github.com/sbb-design-systems/sbb-angular/assets/26955394/52af56fb-a0a2-4d2a-9644-9420f6df7bf3)

### Steps to reproduce the issue

1. use an ipad Device with mentioned version 
2. goto https://sbb.ch
3. search for an international connection, e.g. Zürich --> Paris
4. choose a train-connection
5. click on "Kaufen"
6. in the following screen choose "als Gast"
7. enter valid data for a traveller 
8. check the "Informationen zu Klassen und Tarifkonditionen" link 

**Expected behavior**
Icon should be visible 

Note: This doesn't happen with newer versions

**Comment by mhaertwig** [comment] 2023-07-05 16:26
The problem is the space in the **" Information zu Klassen und Tarifkonditionen "** text.

![image](https://github.com/sbb-design-systems/sbb-angular/assets/3184240/2aa367c3-c483-479a-a632-2de08fdc4020)

After removing this space the arrow is displayed correctly.

![image](https://github.com/sbb-design-systems/sbb-angular/assets/3184240/3882f1f4-39b0-4ba0-873f-b19760514c33)

It seems like this was a bug in Safari that was fixed in the meantime. 

@thm912, may I kindly ask you to create a bug report for the Webshop team and to ask them to remove the spaces around the text? The bug only occurs in Safari versions, which we no longer officially support and I didn't find an easy solution.

I am closing this issue. Feel free to re-open if you don't agree.

**Closed by mhaertwig** 2023-07-05 16:26 UTC
Labels: bug
