### ISSUE TITLE
Bug: Tabbing over select component does not work anymore

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#411] opened 2020-05-13 12:26 UTC
**Describe the bug**
It is not possible to use keyboard navigation in a form with a select.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-lsypsx?file=src%2Fapp%2Fapp.component.html
2. Click on demo page
3. Tab through the elements
4. It is not possible to tab over the first select

**Expected behavior**
It should change focus to the next select.

**Screenshots**

**Additional context**
Bug occurs in version 9.5.0, but did not occur in version 9.0.1. I did not test the versions in between. This affects both public and business.

**Comment by kyubisation** [comment] 2020-05-13 12:31
Duplicate of #383 
Is fixed by #404, which will be released with the next version.

**Closed by kyubisation** 2020-05-13 12:31 UTC
Labels: bug
