### ISSUE TITLE
Bug: search suggestions (SBB Autocomplete) covers input field

### ISSUE THREAD

**Issue by TheScarbon** [sbb-design-systems/sbb-angular#908] opened 2021-11-04 10:42 UTC
**Describe the bug**
On mobile, the search suggestions are displayed above the input during the search, so that the user does not see his input at all. This should be adjusted.

**To Reproduce**
1. Position the input field in the middle of the screen
2. Click on the input field
3. Search something so that the suggestions pop up
4. Try to cover the input field with those suggestions

https://github.com/TheScarbon/angularDropdowns

**Expected behavior**
The autocomplete should always be under the input field and the user should be able to read their input.

**Screenshots**
![IMG_5696](https://user-images.githubusercontent.com/81610601/140299952-ec30c18b-1d27-493c-bbff-98b55abf3c01.PNG)
![IMG_5697](https://user-images.githubusercontent.com/81610601/140299956-48578292-d645-4580-b468-c7543c5f4e34.PNG)

**Smartphone:**
 - Device: iPhone X
 - OS: 14.6
 - Browser: Safari
 - Version 15

**Comment by kyubisation** [comment] 2021-11-04 10:48
Related #335

**Comment by ms007** [comment] 2021-12-01 16:38
Can also be reproduced with Angular 13 and @sbb-esta/angular (RC2)

**Comment by ivanParanor** [comment] 2021-12-15 12:25
Same here.       
Options pane seems to be displaced every time when device keyboard appears.   
 
- sbb toolkit 12.4
- Device Ipad 6 gen
- OS 14.2
- Safari, Chrome, Edge

(reproduced with sbb toolkit only, in **angular material 12.2.2** works as expected)

![image](https://user-images.githubusercontent.com/96182941/146185001-d2566f79-73d8-4f30-9b07-c0e8a5ba9e92.png)

![image](https://user-images.githubusercontent.com/96182941/146186351-7407f4eb-1315-49f3-a320-801756a8b919.png)

**Comment by jeripeierSBB** [comment] 2022-01-04 15:05
This PR might solve this issue: https://github.com/angular/components/pull/24160

**Comment by jeripeierSBB** [comment] 2022-01-17 11:44
Fixed by [#angular/components#24160 ](https://github.com/angular/components/pull/24160). Please update your @angular/cdk dependency to at least version 13.1.2

**Closed by jeripeierSBB** 2022-01-17 11:44 UTC
Labels: bug, effort2: days, prio3: medium, comp: angular
