### ISSUE TITLE
[Bug]: sbb-toggle element fires change event when initialized

### ISSUE THREAD

**Issue by U239087** [sbb-design-systems/sbb-angular#2041] opened 2023-10-09 12:56 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

16.6.0

### Operating system

Windows 10

### Browser / Browser version

Google Chrome 117.0.5938.134 (64-bit)

### Input mode

Mouse/Keyboard

### What happened?

(change) event of a sbb-toggle element gets fired after being rendered again by a true *ngIf statement.

Stackblitz to reproduce: 
https://stackblitz.com/edit/aptgq5?file=src%2Fapp%2Ftoggle-without-form-example.ts,src%2Fapp%2Ftoggle-without-form-example.html

What did I expect to happen:
I expected that it would at least hold the previous value but it always emits the first sbb-toggle-option elements value.

### Steps to reproduce the issue

1. Create div element with simple *ngIf directive.
2. Set a boolean condition on that div, which can be toggled via external button
3. Place a sbb-toggle element inside said div element.
4. Add (change) eventEmitter and log the results to console
5. Add some sbb-toggle-option element inside sbb-toggle element
6. Click external button to trigger *ngIf condition

### Relevant log output

```shell
No relevant log output.
```

**Comment by mhaertwig** [comment] 2023-10-09 14:28
@U239087 thanks for the bug report. However, I think that's the expected behavior:

The toggle requires an option to be selected. If you don't select an option, the `SbbToggle` automatically selects the first option and notifies you by firing an `change` event. When you load the component the first time, you already see the log output of this change event.

When you hide and show the component using `NgIf`, the exact same thing occurs: The component is rendered again and because it has no initial value, it selects the first one and fires a `change` Event.

To avoid this, you can use an `ngModel` or a `FormControl` to set the initial value for the `sbb-toggle` element: https://stackblitz.com/edit/aptgq5-ybu9bs?file=src%2Fapp%2Ftoggle-without-form-example.ts,src%2Fapp%2Ftoggle-without-form-example.html

I will add a note to our documentation that describes this behavior and close this bug report. Feel free to re-open if you have further questions.

**Closed** 2023-10-10 08:58 UTC
Labels: bug
