### ISSUE TITLE
Bug: Autocomplete displayWith is invoked for input values as well

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#380] opened 2020-04-27 09:52 UTC
**Describe the bug**
Starting with v9 the `displayWith` function of the autocomplete is invoked for input values as well. Before it was only invoked for selected option values (assuming the form control value was never set explicitly).

This leads to problems, as many displayWith functions do not expect a string, but only the objects for the options values. 

**To Reproduce**
1. ng serve ssh://git@code.sbb.ch:7999/mvg_dks/cargo-hub-ui.git
2. add some logging in `ZkkSelectionComponent.display`
3. http://localhost:4200/auth/zkkSelection (auth with any dummy value)
4. enter 450
5. observe that `display` is invoked with `"450"`

**Expected behavior**
The displayWith function should not be invoked with input strings, but only with selected option values. (as with pre v9)

**Desktop (please complete the following information):**
 - OS: win
 - Browser: Chrome
 - Version: 81

**Comment by kyubisation** [comment] 2020-05-15 15:51
This is an extremly complicated bug and it might be a problem due to Angular Ivy.
I've tried and failed to reproduce the issue in isolation: https://stackblitz.com/edit/angular-sbb-r6zmfn?file=src%2Fapp%2Fapp.component.ts

The reason why this happens, is because due to _something_, the change detection in FormControlDirective is triggered and a change for the [formControl] input is detected, even though it's the same FormControl instance.

This can be reproduced by the following steps:
1. ng serve
2. http://localhost:4200/auth/zkkSelection (auth with any dummy value)
3. Open console and go to sources
4. Open webpack:///./node_modules/@angular/forms/fesm5/forms.js (In chrome hit CTRL+P and type in forms.js)
5. Look for FormControlDirective.prototype.ngOnChanges and add a breakpoint on the first method line
6. enter 450
7. See the breakpoint is reached (enter `changes.form.previousValue === changes.form.currentValue` in the console, which returns true)

Maybe #417 is going to fix it, but I doubt it.

**Comment by kyubisation** [comment] 2020-05-18 14:19
Unfortunately #417 (released in 9.6.0) also does not help.
I'm not quite sure what to do. The problem does not seem related to our implementation, so there is very little we can do.

**Comment by daniel-sc** [comment] 2020-05-18 14:31
Hi @kyubisation 
`displayWith` is invoked by this lib, hence there could be a filter/if so that it is not invoked for the described situation?

**Comment by kyubisation** [comment] 2020-05-18 14:43
The problem is we cannot know what you expect. It is entirely possible a consumer expects a string, which might be exactly the input that was typed.

**Comment by daniel-sc** [comment] 2020-05-18 14:51
Ok - then maybe just update docs to reflect the possibly that this method
is invoked for user (text) input as well!?

kyubisation <notifications@github.com> schrieb am Mo. 18. Mai 2020 um 16:44:

**Comment by kyubisation** [comment] 2020-05-18 14:55
Yes, we can do that. However, as far as I know the cargo-hub-ui project is the only one where this happens and I suspect it has something to do with another component/library/setup that interferes here.
Because as mentioned, I could not reproduce it in isolation: https://stackblitz.com/edit/angular-sbb-r6zmfn?file=src%2Fapp%2Fapp.component.ts (and I really tried)
If another project had this problem, we might have a better change at figuring out the problem.

**Comment by daniel-sc** [comment] 2020-05-19 09:02
Did you succeed to create a stackblitz with the latest versions of SACL and Angular?

**Comment by kyubisation** [comment] 2020-05-19 09:18
Sorry, it seems I did not correctly save the changes in Stackblitz. 😞 
Yes, I created a Stackblitz with a similar setup as your ZkkSelectionComponent and could not reproduce the issue.

**Comment by kyubisation** [comment] 2020-07-02 13:37
We will close this for now. If another project can reproduce it or an isolated reproduction on stackblitz can be provided, we will have another look.

**Closed by kyubisation** 2020-07-02 13:37 UTC
Labels: bug, comp: business, comp: public
